name: Ultimate Daily Update - Final Resort

on:
  workflow_dispatch:    # allows manual run
  schedule:
    - cron: "0 12 * * *"  # daily at 12:00 UTC

jobs:
  daily-update:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false   # we use PAT manually

      # 2. Create or update a daily quote file
      - name: Add daily quote
        run: |
          echo "Your ultimate daily quote for $(date)" > daily-quote.txt

      # 3. Commit & push changes using PAT
      - name: Commit & push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add daily-quote.txt
          git commit -m "Ultimate daily update $(date)" || echo "No changes"
          git push https://$PAT_TOKEN@github.com/FatlumDili/metal_production_algorithm.git main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
