name: Ultimate Repo Automation

on:
  schedule:
    - cron: "0 12 * * *"  # daily at 12:00 UTC
  workflow_dispatch:      # allows manual run

jobs:
  super-update:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2. Update README with timestamp
      - name: Update README
        run: |
          echo "Last updated: $(date)" > last_update.txt
          echo "" >> last_update.txt
          cat README.md >> last_update.txt
          mv last_update.txt README.md

      # 3. Add a daily random quote
      - name: Add daily quote
        run: |
          QUOTE=$(curl -s https://api.quotable.io/random | jq -r '.content')
          echo "$QUOTE" > daily-quote.txt

      # 4. Setup Python and install packages
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install black

      # 5. Auto-format Python code
      - name: Format Python code
        run: black . --line-length 88 || echo "No formatting changes"

      # 6. Commit everything
      - name: Commit & Push
        run: |
         git config user.name "GitHub Actions"       
         git config user.email "actions@github.com"  
         git add daily-quote.txt metal_inventory.ipynb README.md
         if git diff --cached --quiet; then
          echo "Daily timestamp $(date)" >> daily-quote.txt
          git add daily-quote.txt
         fi
         git commit -m "Ultimate daily update $(date)" || echo "No changes"
         git push https://x-access-token:${PAT_TOKEN}@github.com/FatlumDili/metal_production_algorithm.git main
          env:
           PAT_TOKEN: ${{ secrets.automation }}
