name: Ultimate Daily Automation with Debug

on:
  workflow_dispatch:    # allows manual run
  schedule:
    - cron: "0 12 * * *"  # daily at 12:00 UTC

jobs:
  daily-update:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false   # we’ll use PAT manually

      # 2. Debug: Show working directory and files
      - name: Debug Repo State
        run: |
          echo "Current directory:"
          pwd
          echo "Files:"
          ls -la

      # 3. Update README (example)
      - name: Update README
        run: |
          echo "Last updated: $(date)" >> README.md

      # 4. Run Python script (metal production project)
      - name: Run Metal Production Script
        run: |
          python3 metal_production.py

      # 5. Add daily quote
      - name: Add Daily Quote
        run: |
          echo "Your ultimate daily quote for $(date)" > daily-quote.txt

      # 6. Debug: Show Git status before commit
      - name: Git Status & Diff
        run: |
          git status
          git diff

      # 7. Commit & push changes using PAT
      - name: Commit & Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add README.md daily-quote.txt
          git add metal_production.py  # if your script updates itself
          git commit -m "Ultimate daily update $(date)" || echo "No changes to commit"
          git log -1
          git push https://$PAT_TOKEN@github.com/FatlumDili/metal_production_algorithm.git main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
